module.exports = [
  'Malware Development',
  'HackTheBox',
  'Reverse Engineering',
  'Network+',
  'PenTest+',
  'iOS & Swift',
  'Web Development',
  'CySA+',
  'Assembly',
  'C',
  'C++',
  'Python',
  'Go',
  'Rust',
  'Android Development',
  'Books: Attacking Network Protocols',
  'Books: Black Hat Go',
  'Books: Foundations of Information Security',
  'Books: Hacking The Art of Exploitation 2nd Edition',
  'Books: Linux Basics  for Hackers',
  'Books: Malware Data Science',
  'Books: Metasploit A Penetration Testers Guide',
  'Books: Penetration Testing',
  'Books: Practical Binary Analysis',
  'Books: Practical Malware Analysis',
  'Books: Practical Packet Analysis',
  'Books: Real-World Bug Hunting',
  'Books: Rootkits and Boot kits',
  'Books: Serious Cryptography',
  "Books: The Car Hacker's Handbook",
  'Books: The Hardware Hacker',
  'Books: The Linux Command Line',
  'Books: Web Security For Developers',
  'Books: Applied cryptography protocols algorithms and source code in C',
  'Books: Art of intrusion the real stories behind the exploits of hackers intruders',
  'Books: Art of memory forensics detecting malware and threats in windows Linux and mac memory',
  'Books: Cryptography engineering design principles and practical applications',
  'Books: Liars and out liers enabling the trust that society needs to thrive',
  'Books: Malware analysts cookbook',
  'Books: Practical reverse engineering x86 x64 arm windows kernel reversing tools and obfuscation',
  'Books: Secrets and lies digital security in a Network ed world',
  'Books: Shell coders handbook discovering and exploiting security holes',
  'Books: Social engineering the science of human hacking 2nd edition',
  'Books: The art of deception controlling the human element of security',
  'Books: Threat modeling designing for security',
  'Books: Unauthorized access physical penetration testing for it security teams',
  'Books: Web application hackers handbook finding and exploiting security flaws',
  'Books: We have root even more advice from Schneider on security',
  'Books: Learning Python',
  'Books: Automate the Boring Stuff with Python',
  'Books: Secrets of Reverse Engineering',
  'Books: Modern x86 Assembly Language',
  "Books: Gray Hat Hacking The Ethical Hacker's Handbook",
  'Books: Practice of Network security monitoring',
  'Books: The IDA Pro Book 2nd Edition',
  'Books: Designing BSD rootkits',
  'Books: Bug hunters diary',
  'Books: Cyber jujitsu',
  'Books: C Programming Language',
  'Books: Red Team Development and Operations',
  'Advanced Exercises CTF Four Targets',
  'Advanced Exercises CTF Mega Mystery',
  'Advanced Exercises CTF One Target',
  'Advanced Exercises CTF Three Targets',
  'Advanced Exercises CTF Two Targets',
  'Advanced Exercises Weekly CTF',
  'Advanced Priv-Esc Linux App Armor',
  'Advanced Priv-Esc Linux Linux Capabilities',
  'Advanced Priv-Esc Linux Sec comp',
  'Advanced Priv-Esc Windows DLL Hijacking',
  'Advanced Priv-Esc Windows UAC Bypass',
  'CloudSecurity AWS CloudSecurity Dynamo DB',
  'CloudSecurity AWS CloudSecurity S3',
  'Container Security Container Breakouts',
  'Container Security Docker APIFirewall',
  'Container Security Docker Host Attacks ',
  'Container Security Docker ImageSecurity Docker Forensics',
  'Container Security Docker ImageSecurity Docker ImageAnalysis',
  'Container Security Docker ImageSecurity Docker Registry',
  'Container Security Docker ImageSecurity Docker fileLinting',
  'Container Security Intro to Container Basics ',
  'Container Security Intro to Docker MicroServices',
  'Container Security Miscellaneous Docker Security Tools',
  'DevOps Basics Building Project',
  'DevOps Basics Continuous Integration',
  'DevOps Basics Infrastructure as Code',
  'DevOps Basics Version Control Systems',
  'Basics Automated Code Review',
  'Basics Compliance as Code',
  'Basics Dynamic Application Security Testing',
  'Basics Sensitive Information Scan',
  'Basics Software Composition Analysis',
  'Basics Static Application Security Testing',
  'Fix The Code Web Applications',
  'Pipeline Basics Software',
  'Pipeline Basics Web Applications',
  'Forensics Disk Forensics Basics ',
  'Forensics Memory Forensics Basics ',
  'IoT Security Device Attacks Boot loader',
  'IoT Security Network Attacks AMQP',
  'IoT Security Network Attacks MQTT',
  'Linux Security Exploit Research Buffer Overflow',
  'Linux Security Exploitation Metasploit',
  'Linux Security Exploitation Password Cracking ',
  'Linux Security Exploitation Web Applications',
  'Linux Security Linux Basics Basics ',
  'Linux Security MITRE ATTACK Broken Access Control',
  'Linux Security MITRE ATTACK Broken Authentication',
  'Linux Security MITRE ATTACK Command and Control',
  'Linux Security MITRE ATTACK Credential Access',
  'Linux Security MITRE ATTACK Cross Site Scripting',
  'Linux Security MITRE ATTACK Defense Evasion',
  'Linux Security MITRE ATTACK Discovery 3 Labs',
  'Linux Security MITRE ATTACK Injection',
  'Linux Security MITRE ATTACK Insecure Deserialization',
  'Linux Security MITRE ATTACK Insufficient Logging',
  'Linux Security MITRE ATTACK Lateral Movement',
  'Linux Security MITRE ATTACK Persistence',
  'Linux Security MITRE ATTACK Privilege Escalation',
  'Linux Security MITRE ATTACK Security Misconfiguration',
  'Linux Security MITRE ATTACK Sensitive Data Exposure',
  'Linux Security MITRE ATTACK Vulnerable Components',
  'Linux Security MITRE ATTACK XML External Entities',
  'Linux Security Maintaining Access Basics ',
  'Linux Security Pivoting Basics ',
  'Linux Security Post Exploitation Browser Forensics',
  'Linux Security Post Exploitation Lateral Movement',
  'Linux Security Post Exploitation Metasploit Post Modules',
  'Linux Security Privilege Escalation Basic',
  'Linux Security Reconnaissance DNS',
  'Linux Security Reconnaissance FTP Servers',
  'Linux Security Reconnaissance Memcached',
  'Linux Security Reconnaissance SQL Databases',
  'Linux Security Reconnaissance Web Applications',
  'Linux Security Reconnaissance Webservers',
  'Offensive Python Interacting with Files File Metadata',
  'Offensive Python Interacting with Files PCAP Analysis',
  'Offensive Python Interacting with Files Password Cracking ',
  'Offensive Python Live Interactions Client Emulation',
  'Offensive Python Live Interactions Debugging',
  'Offensive Python Live Interactions Server Attacks ',
  'Offensive Python Live Interactions Server Emulation',
  'Android Pentesting Basics ',
  'Code Repositories APT Repository',
  'Code Repositories Git',
  'Code Repositories Python PyPi',
  'Deliberately Vulnerable Web Apps ',
  'CI/CD Tools',
  'Endpoint Security HIDS',
  'Endpoint Security MalwareScanner',
  'Endpoint Security OSQueryMITRE',
  'Endpoint Security Sysdig',
  'Endpoint Security osquery',
  'Firmware Analysis Wi-Fi Routers',
  'Forensics Browser',
  'Infrastructure Attacks Apache',
  'Infrastructure Attacks Memcached',
  'Infrastructure Attacks MongoDB',
  'Infrastructure Attacks Nginx',
  'Infrastructure Attacks Squid Proxy',
  'Linux Runtime Analysis Profiling Tools',
  'Log Analysis DNS Logs',
  'Log Analysis Other Tools',
  'Log Analysis ProxyLogs',
  'Log Analysis SSH Logs',
  'Log Analysis Webserver Logs',
  'Log Analysis Windows Event Logs',
  'MITRE ATTACK Linux Credential Access',
  'MITRE ATTACK Linux Discovery',
  'MITRE ATTACK Linux Persistence',
  'MITRE ATTACK Linux Privilege Escalation ',
  'Malware Analysis Simple Samples',
  'Metasploit Auxiliary Modules',
  'Metasploit Latest Targets',
  'Metasploit Linux Exploitation',
  'Metasploit CTFs',
  'Metasploit Pivot CTFs',
  'Metasploit Meterpreter',
  'Metasploit Pivoting',
  'Metasploit Post Modules',
  'Metasploit WebApp Exploits',
  'Metasploit Windows Apps Exploits',
  'Metasploit Word Press Exploitation',
  'Network Pentesting DNS',
  'Network Pentesting Git',
  'Network Pentesting Recon ',
  'Network Pentesting Subversion',
  'Network Pivoting Single Pivots',
  'Network Recon Distributed Databases',
  'Network Recon Distributed Queues',
  'Network Recon Finger Servers',
  'Network Recon IMAP Servers',
  'Network Recon IRC Servers',
  'Network Recon NTP Servers',
  'Network Recon NoSQL Databases',
  'Network Recon POP3 Servers',
  'Network Recon Proxy Servers',
  'Network Recon RADIUS',
  'Network Recon SIEM Platforms',
  'Network Recon SMB Servers',
  'Network Recon SMTP Servers',
  'Network Recon SNMP',
  'Network Recon SQL Databases',
  'Network Recon SSH Servers',
  'Network Recon TFTP Servers',
  'Network Recon Telnet Servers',
  'Network Recon VNC',
  'Network Recon Webservers',
  'OWASP Top 10 Single Page Applications',
  'Persistence Data Ex-filtration',
  'Persistence Maintaining Access',
  'Privilege Escalation App to Root',
  'Privilege Escalation Linux ',
  'Privilege Escalation Linux Capabilities',
  'Privilege Escalation Web to Root',
  'REST API Security',
  'REST GraphQL',
  'REST JWT Advanced',
  'REST JWT Basics ',
  'REST JWT Expert',
  'Web Apps Arbitrary File Download',
  'Web Apps Broken Authentication',
  'Web Apps CSRF',
  'Web Apps Command Injection',
  'Web Apps Directory Traversal',
  'Web Apps File Upload',
  'Web Apps Local File Inclusion',
  'Web Apps Reflected XSS',
  'Web Apps Remote Code Execution',
  'Web Apps SQL Injection',
  'Web Apps SSRF',
  'Web Apps SSTI',
  'Web Apps Stored XSS',
  'Web Apps XML External Entity',
  'Secure Coding Python ',
  'Secure Coding Ruby',
  'Service Exploitation Linux Services',
  'Service Exploitation WebApp Frameworks',
  'traffic Analysis TsharkFu',
  'Web Technologies Bot Attack',
  'Web Technologies Web Sockets',
  'Web App CVEs 2016',
  'Web App CVEs 2017',
  'Web App CVEs 2018',
  'Web App CVEs 2019',
  'Web App CVEs 2020',
  'Web App CVEs 2021',
  'Web App CVEs 2022',
  'Web App Older CVEs',
  'Password Cracking File Passwords Basics ',
  'Password Cracking Hashes Basics ',
  'Reverse Engineering Linux GDB Basics ',
  'Reverse Engineering Linux Static Binary Analysis',
  'Reverse Engineering WindowsBasics ',
  'Web App Pentesting Basics Tools of the Trade Basics ',
  'Web App Pentesting Basics Web Application Basics',
  'Web App Pentesting Basics CVEsBasics ',
  'WiFi Security Advanced Labs AP Back-doors',
  'WiFi Security Advanced Labs Custom Firmware',
  'WiFi Security Advanced Labs Python Scripting',
  'WiFi Security Basics AP Client Basics ',
  'WiFi Security Basics Open WRT Router',
  'WiFi Security Basics Reconnaissance ',
  'WiFi Security Basics Tools',
  'WiFi Security Basics Traffic Analysis',
  'WiFi Security Enterprise Networks Live Cracking',
  'WiFi Security Enterprise Networks Offline Cracking',
  'WiFi Security Enterprise Networks WiFi Pivoting',
  'WiFi Security Forensics Basics ',
  'WiFi Security Personal Networks Live Cracking',
  'WiFi Security Personal Networks Offline Cracking',
  'Windows Security Basic Exploitation With Metasploit ',
  'Windows Security Maintaining Access Basics ',
  'Windows Security Post Exploitation With Metasploit ',
  'Windows Security Privilege  Escalation  Basic',
  'Windows Security Reconnaissance  Host Discovery',
  'Windows Security Reconnaissance  SMB',
  'Windows Security Service Exploitation RDP',
  'Windows Security Service Exploitation SMB',
  'Windows Security Service Exploitation WMI',
  'Windows Security Service Exploitation WinRM',
];
